[package]
edition = "2021"
name = "bevy_polyline"
version = "0.1.0"

[dependencies]
bitflags = "1.3"
bevy = "0.6"

[dependencies.naga]
features = ["glsl-in", "spv-out", "wgsl-out"]
version = "*"

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.8.4"
ringbuffer = "0.8.2"
